version: "3.9"

services:

  vscode:
    image: steedos/vscode-server
    ports:
      - "5555:3000"
      - "5000:5000"
      - "3001:3001" 
    environment:
      - MONGO_URL=mongodb://mongodb:27017/steedos
      - MONGO_OPLOG_URL=mongodb://mongodb:27017/local
      - TRANSPORTER=redis://redis:6379/1
      - CACHER=redis://redis:6379
    depends_on:
      mongodb-init:
        condition: service_started
    volumes:
      - '.:/home/workspace/steedos-platform:cached'
      
  redis:
    image: redis:6.2
    command: ["redis-server", "--save", "--appendonly no",  "--loglevel warning"]  # disable persistence
    ports:
      - "6379:6379"
  
  mongodb:
    image: mongo:4.4
    ports:
      - 27017:27017
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "steedos" ]
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo --quiet | grep 1
      interval: 10s
      timeout: 10s
      retries: 5
    volumes:
      - 'steedos-mongo-data:/data/db'

  mongodb-init:
    image: mongo:4.4
    restart: "no"
    depends_on:
      mongodb:
        condition: service_healthy
    command: >
      mongo --host mongodb:27017 --eval "rs.initiate({ _id: 'steedos', members: [{_id: 0, host: 'mongodb:27017'}]})"



volumes:
  steedos-mongo-data:
    driver: local