version: "3.9"

services:

  vscode:
    image: steedos/vscode-server:1.76
    ports:
      - "3000:3000"
      - "5100:5100"
    environment:
      - PORT=5100
      - ROOT_URL=http://127.0.0.1:5100
      - MONGO_URL=mongodb://mongodb:27017/steedos
      - MONGO_OPLOG_URL=mongodb://mongodb:27017/local
      - TRANSPORTER=redis://redis:6379/1
      - CACHER=redis://redis:6379
    volumes:
      - '.:/home/workspace/steedos-platform'
      
  redis:
    image: redis:6.2
    ports:
      - "6379:6379"
  
  mongodb:
    image: mongo:4.4
    ports:
      - 27017:27017
    command: --replSet steedos
    healthcheck:
      test: echo 'rs.initiate(); db.runCommand("ping").ok' | mongo --quiet | grep 1
      interval: 10s
      timeout: 10s
      retries: 5
    volumes:
      - 'steedos-mongo-data:/data/db'

volumes:
  steedos-mongo-data:
    driver: local