version: "3.9"

services:

  steedos:
    image: steedos/steedos-community:2.4
    ports:
      - "5000:5000"
    env_file:
      - .env.local
    environment:
      - PORT=5000
      - MONGO_URL=mongodb://mongodb:27017/steedos
      - MONGO_OPLOG_URL=mongodb://mongodb:27017/local
      - TRANSPORTER=nats://nats:4222
      - CACHER=redis://redis:6379
    depends_on:
      mongodb:
        condition: service_healthy
        
  redis:
    image: redis:6.2
    ports:
      - "6379:6379"
  
  mongodb:
    image: mongo:4.4
    ports:
      - 27017:27017
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "steedos" ]
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo --quiet | grep 1
      interval: 10s
      timeout: 10s
      retries: 5
    volumes:
      - 'steedos-mongo-data:/data/db'

  mongodb-init:
    image: mongo:4.4
    restart: "no"
    depends_on:
      mongodb:
        condition: service_healthy
    command: >
      mongo --host mongodb:27017 --eval "rs.initiate({ _id: 'steedos', members: [{_id: 0, host: 'mongodb:27017'}]})"

  # Micro Service Transporter
  nats:
    image: bitnami/nats
    ports:
      - "4222:4222"
      - "8222:8222" # monitor port

volumes:
  steedos-mongo-data:
    driver: local