datasources:
  default:
    connection: 
      url: ${MONGO_URL}
public:
  cfs:
    store: "local"
    local: 
      folder: "./storage"
  templateSpaceId: template
plugins:
  - "@steedos/plugin-enterprise"
enable_holidays: true
STEEDOS_STORAGE_DIR: "./storage"
tenant:
  _id: ${ENV_TENANT_ID}
  saas: false
  enable_mobile: false
  enable_register: true
  enable_forget_password: false
  enable_password_login: true