blank_issues_enabled: false
contact_links:
  - name: ğŸ¤” Questions and Help é—®é¢˜å’¨è¯¢å’Œè®¨è®º
    url: https://github.com/orgs/steedos/discussions
    about: Reach out to us github discussions page. è¯·è®¿é—® Github Discussions é¡µé¢
  - name: ğŸ“ Contact us è”ç³»æˆ‘ä»¬
    url: https://console.steedos.cn/api/files/images/YRgRK94fwndMxMcjM
    about: ä½¿ç”¨å¾®ä¿¡æ‰«ç åŠ å…¥å¼€å‘è€…æœåŠ¡ç¾¤ï¼Œæˆ–æ˜¯å’¨è¯¢å•†åŠ¡é—®é¢˜ã€‚