env:
  PORT: 5000
  ROOT_URL: http://127.0.0.1:5000/
datasources:
  default:
    connection:
      url: mongodb://127.0.0.1/steedos
public:
  cfs:
    store: "local"
    local:
      folder: "./storage"
cron:
  instancerecordqueue_interval: 10000
plugins: 
webservices:
  steedos: /
tenant: 
  _id: 