version: "3.9"

services:

  redis:
    image: redis:6.2
    command: "redis-server --save \"\" --appendonly no --loglevel warning"
    ports:
      - "6379:6379"
  
  mongodb:
    image: 'bitnami/mongodb:4.4'
    restart: on-failure
    ports:
      - 27017:27017
    environment:
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_PORT_NUMBER=${MONGODB_PORT_NUMBER:-27017}
      - MONGODB_INITIAL_PRIMARY_HOST=${MONGODB_INITIAL_PRIMARY_HOST:-mongodb}
      - MONGODB_INITIAL_PRIMARY_PORT_NUMBER=${MONGODB_INITIAL_PRIMARY_PORT_NUMBER:-27017}
      - MONGODB_REPLICA_SET_NAME=${MONGODB_REPLICA_SET_NAME:-steedos}
      - MONGODB_ENABLE_JOURNAL=${MONGODB_ENABLE_JOURNAL:-true}
      - MONGODB_ADVERTISED_HOSTNAME=${MONGODB_ADVERTISED_HOSTNAME:-mongodb}
      - ALLOW_EMPTY_PASSWORD=${ALLOW_EMPTY_PASSWORD:-yes}
    volumes:
      - 'steedos-mongo-data:/bitnami'

  postgres:
    image: postgres:11
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-keycloak}
      - POSTGRES_USER=${POSTGRES_USER:-keycloak}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-keycloak}
    volumes:
      - 'postgres_data:/var/lib/postgresql/data'

volumes:
  steedos-mongo-data:
  postgres_data:
      driver: local