name: Docker Enterprise

on:
  workflow_run:
    workflows: [Release NPM]
    types:
      - completed
  push:
    branches:
      - 'release/**'

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      # checkout branch 2.7
      # - name: Checkout branch 2.7
      #   uses: actions/checkout@v2
      #   if: ${{ startsWith(steps.branch-name.outputs.tag, '2.7') }} 
      #   with: 
      #     ref: '2.7'
      
      # checkout branch 2.6
      - name: Checkout branch 2.6
        uses: actions/checkout@v2
        with: 
          ref: '2.6'

      - uses: nowsprinting/check-version-format-action@v3
        id: version
        with:
          prefix: 'v'

      - name: Set Current Version
        run: |
          STEEDOS_VERSION=$(node -p 'require("./lerna.json").version')
          echo "STEEDOS_VERSION=${STEEDOS_VERSION}" >> $GITHUB_ENV
          echo "STEEDOS_VERSION=${STEEDOS_VERSION}"
        
      - name: Generate info.json
        run: |
          if [[ -f deploy/enterprise/scripts/generate_info_json.sh ]]; then
            deploy/enterprise/scripts/generate_info_json.sh
          fi

      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
        with:
          driver-opts: network=host
          
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            steedos/steedos-enterprise
            252208178451.dkr.ecr.cn-northwest-1.amazonaws.com.cn/dockerhub/steedos/steedos-enterprise
          tags: |
            type=semver,pattern={{version}},value=${{ env.STEEDOS_VERSION }}
            type=semver,pattern={{major}}.{{minor}},value=${{ env.STEEDOS_VERSION }}
            type=semver,pattern={{major}},value=${{ env.STEEDOS_VERSION }}

      - uses: docker/login-action@v1
        name: Login Docker Hub
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_NINGXIA }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_NINGXIA }}
          aws-region: cn-northwest-1
      -
        name: Login to ECR
        uses: docker/login-action@v2
        with:
          registry: 252208178451.dkr.ecr.cn-northwest-1.amazonaws.com.cn

      - name: Replace Version ~2.7 to Tag
        uses: jacobtomlinson/gha-find-replace@v2
        with:
          include: deploy/enterprise/app/platform/package.json
          find: "~2.7"
          replace: ${{env.STEEDOS_VERSION}}
          regex: false

      - name: Build and push docker
        uses: docker/build-push-action@v3
        if: ${{ steps.version.outputs.is_stable != 'true' }}
        with:
          context: ./deploy/enterprise
          platforms: linux/amd64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      # 正式版才发布 arm64
      - name: Build and push docker
        uses: docker/build-push-action@v3
        if: ${{ steps.version.outputs.is_stable == 'true' }}
        with:
          context: ./deploy/enterprise
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

