# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Publish Latest Steedos Platform

on:
  push:
     branches:
       - publish-latest
  # push:
  #   tags:
  #     - 'v**'
jobs:
  release:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      # - name: Checkout branche
      #   run: |
      #     git checkout next
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"
      - uses: meteorengineer/setup-meteor@v1
        with:
          meteor-release: '1.9.3'
      - run: yarn --frozen-lockfile
      - run: yarn bootstrap
      - name: Build creator
        run: |
          yarn build_creator
      - name: Push creator build
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add . 
          git commit -m creator build
          git push
      - name: Lerna version
        run: |
          lerna version patch --no-git-tag-version --force-publish --exact --yes
      - name: Set Current Version
        run: |
          CURRENT_VERSION=$(node -p 'require("./lerna.json").version')
          echo "CURRENT_VERSION=${CURRENT_VERSION}" >> $GITHUB_ENV
      - name: Create commits & Push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add . 
          git commit -m v${{ env.CURRENT_VERSION }}
          git push
      - name: Create Tag
        run: |
          git tag -a v${{ env.CURRENT_VERSION }} -m 'published v${{ env.CURRENT_VERSION }}' 
          git push origin --tags
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: v${{ env.CURRENT_VERSION }}
          release_name: v${{ env.CURRENT_VERSION }}
          draft: false
          prerelease: false
      - name: Lerna publish
        run: |
          npm config set //registry.npmjs.org/:_authToken=$NODE_AUTH_TOKEN
          lerna publish from-package --yes --dist-tag next
        env:
          CI: true
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
